runtime: python39

handlers:
- url: /(.+\.(css|js|html|png|jpg|ico|svg|ttf|woff|woff2|json))
  static_files: dist/bob/\1
  upload: dist/bob/.*\.(css|js|html|png|jpg|ico|svg|ttf|woff|woff2|json)

- url: /.*
  static_files: dist/bob/index.html
  upload: dist/bob/index.html